[package]
name = "elf-code"
version = "0.1.0"
authors = ["Felix Kohlgrüber <felix.kohlgrueber@gmail.com>"]
edition = "2018"

[[bin]]
name = "elf-code"
path = "data.rs"

[dependencies]
petgraph = "0.4.13"